### ISSUE TITLE
Kafka connect - getting Connect Timed Out for Google GCS sink connector

### ISSUE THREAD

**Issue by alexanghel23** [aiven/gcs-connector-for-apache-kafka#117]
Hello,

Please help me sort out an error i keep getting when trying to connect a topic to Google Cloud Storage.
I am running the Strimzi operator in a Kubernetes cluster behind a proxy. I have followed [this](https://strimzi.io/docs/operators/latest/using.html#proc-configuring-proxy-config-cluster-operator-str) guide and set up the https_proxy and http_proxy env variables in the strimzi operator deployment yaml.

However, when launching the connector keep getting this error:
[error.txt](https://github.com/aiven/gcs-connector-for-apache-kafka/files/7881634/error.txt)

I have also set up the proxy env variables in the Kafka connect cluster. Any ideas for a fix?

Thank you!

**Comment by tvainika** [comment]
The error log you added contains failure to connect with OAuth provider. I assume there some mismatches with the authentication configuration in your setup. See this part:
```
Caused by: java.io.IOException: Error getting access token for service account: connect timed out
at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:401)
at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:181)
at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:167)
at com.google.auth.http.HttpCredentialsAdapter.initialize(HttpCredentialsAdapter.java:96)
at com.google.cloud.http.HttpTransportOptions$1.initialize(HttpTransportOptions.java:159)
at com.google.cloud.http.CensusHttpModule$CensusHttpRequestInitializer.initialize(CensusHttpModule.java:109)
at com.google.api.client.http.HttpRequestFactory.buildRequest(HttpRequestFactory.java:93)
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:381)
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:357)
at com.google.cloud.storage.spi.v1.HttpStorageRpc.open(HttpStorageRpc.java:775)
... 25 more
```

I hope this helps. I'm closing this issue as there does not seem to be any issue with the connector itself.
